
services:
  web:
    image: olegdayo/secdev-app:9db4adc2b903a8f6b9a699e57892140597e7afb9
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - APP_NAME=secdev-seed
      - DEBUG=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 3s
      retries: 5
